import type { Meal } from "./columns"

export const meals: Meal[] = [
  {
    id: "M001",
    studentId: "S12345",
    studentName: "John Doe",
    type: "Breakfast",
    mealPlan: "Standard",
    date: "2023-05-09",
    time: "08:15 AM",
    status: "Served",
  },
  {
    id: "M002",
    studentId: "S12346",
    studentName: "Jane Smith",
    type: "Lunch",
    mealPlan: "Vegetarian",
    date: "2023-05-09",
    time: "12:30 PM",
    status: "Served",
    specialRequest: "No onions",
  },
  {
    id: "M003",
    studentId: "S12347",
    studentName: "Michael Johnson",
    type: "Dinner",
    mealPlan: "Standard",
    date: "2023-05-09",
    time: "06:45 PM",
    status: "Pending",
  },
  {
    id: "M004",
    studentId: "S12348",
    studentName: "Emily Williams",
    type: "Breakfast",
    mealPlan: "Gluten-Free",
    date: "2023-05-09",
    time: "07:50 AM",
    status: "Served",
    specialRequest: "Gluten-free bread",
  },
  {
    id: "M005",
    studentId: "F12349",
    studentName: "David Brown",
    type: "Lunch",
    mealPlan: "Standard",
    date: "2023-05-09",
    time: "01:15 PM",
    status: "Served",
  },
  {
    id: "M006",
    studentId: "S12350",
    studentName: "Sarah Miller",
    type: "Dinner",
    mealPlan: "Vegetarian",
    date: "2023-05-09",
    time: "07:30 PM",
    status: "Cancelled",
  },
  {
    id: "M007",
    studentId: "F12351",
    studentName: "James Wilson",
    type: "Breakfast",
    mealPlan: "Standard",
    date: "2023-05-10",
    time: "08:00 AM",
    status: "Pending",
  },
  {
    id: "M008",
    studentId: "S12352",
    studentName: "Jessica Taylor",
    type: "Lunch",
    mealPlan: "Vegan",
    date: "2023-05-10",
    time: "12:00 PM",
    status: "Pending",
    specialRequest: "No animal products",
  },
  {
    id: "M009",
    studentId: "S12345",
    studentName: "John Doe",
    type: "Dinner",
    mealPlan: "Standard",
    date: "2023-05-10",
    time: "06:30 PM",
    status: "Pending",
  },
  {
    id: "M010",
    studentId: "S12346",
    studentName: "Jane Smith",
    type: "Breakfast",
    mealPlan: "Vegetarian",
    date: "2023-05-10",
    time: "08:30 AM",
    status: "Pending",
  },
  {
    id: "M011",
    studentId: "S12347",
    studentName: "Michael Johnson",
    type: "Lunch",
    mealPlan: "Standard",
    date: "2023-05-10",
    time: "01:00 PM",
    status: "Pending",
  },
  {
    id: "M012",
    studentId: "S12348",
    studentName: "Emily Williams",
    type: "Dinner",
    mealPlan: "Gluten-Free",
    date: "2023-05-10",
    time: "07:00 PM",
    status: "Pending",
    specialRequest: "Gluten-free pasta",
  },
]
